export const testPhrases = [


{ category: "TUA MAMMA", text: "A FARE I BOCCHINI COL CULO E LA MIGLIORE" },
{ category: "TUA SORELLA", text: "SI CHIAVA GLI ESTINTORI NEL CULO" },
{ category: "COMPLIMENTO SINCERO", text: "APPREZZO LA TUA OSSERVAZIONE SULLA MIA FACCIOTTA STANCA SIGNIFICA MOLTO" },
{ category: "RAPACE NOTTURNO", text: "LA CIVETTA È UN UCCELLO RAPACE CHE CACCIA DI NOTTE" },
];