export const testPhrases = [


{ category: "TUA MAMMA", text: "A FARE I BOCCHINI COL CULO E LA MIGLIORE" },
{ category: "TUA SORELLA", text: "SI CHIAVA GLI ESTINTORI NEL CULO" },
{ category: "IL DONO INASPETTATO", text: "GRAZIE PER QUESTO REGALO CHE HO SEMPRE DESIDERATO MA CHE NON USERÒ MAI" },
{ category: "PERDITA DI MEMORIA", text: "NON RICORDARE PIÙ DOVE SI SONO LASCIATE LE CHIAVI" }, // 44
];